services:
  discord-bot-moderation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot-moderation
    restart: unless-stopped
    stop_grace_period: 60s
    environment:
      # Discord configuration
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}

    # Create a volume for the file sqlite3.db
    volumes:
      - ./sqlite3.db:/app/sqlite3.db
    # Resource limits
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.5'
    #      memory: 256M
    #    reservations:
    #      cpus: '0.25'
    #      memory: 128M
